// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdh-LMzOpqzHqEeXN7uYk0HQWHuajaJfk',
    appId: '1:753661759229:web:3959216c2b88d4191b3894',
    messagingSenderId: '753661759229',
    projectId: 'mom-masale-admin',
    authDomain: 'mom-masale-admin.firebaseapp.com',
    storageBucket: 'mom-masale-admin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoDIgR0gx-9eneXD7ZnCdp7kJJmPIHunw',
    appId: '1:753661759229:android:b03a0aea28c8294a1b3894',
    messagingSenderId: '753661759229',
    projectId: 'mom-masale-admin',
    storageBucket: 'mom-masale-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyRazNAFqBiCV4257k6X7lqhFdrq2Bo4',
    appId: '1:753661759229:ios:4da9f9c723398ad31b3894',
    messagingSenderId: '753661759229',
    projectId: 'mom-masale-admin',
    storageBucket: 'mom-masale-admin.firebasestorage.app',
    iosBundleId: 'com.example.momMasaleAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIyRazNAFqBiCV4257k6X7lqhFdrq2Bo4',
    appId: '1:753661759229:ios:4da9f9c723398ad31b3894',
    messagingSenderId: '753661759229',
    projectId: 'mom-masale-admin',
    storageBucket: 'mom-masale-admin.firebasestorage.app',
    iosBundleId: 'com.example.momMasaleAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdh-LMzOpqzHqEeXN7uYk0HQWHuajaJfk',
    appId: '1:753661759229:web:9a8610b5919101051b3894',
    messagingSenderId: '753661759229',
    projectId: 'mom-masale-admin',
    authDomain: 'mom-masale-admin.firebaseapp.com',
    storageBucket: 'mom-masale-admin.firebasestorage.app',
  );
}
